[package]
name = "spectre_core"
version = "0.1.0"
authors = ["Will Hart <hart.wl@gmail.com>"]
edition = "2018"


[dependencies]
bevy = "0.2" # override in consuming crate

# Local dependencies

spectre_time = { path = "../spectre_time", version = "0.1" }